name: EasyLM
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - pytorch-cpu=1.13.0
    - jax=0.4.7
    - jaxlib=0.4.7=*cuda*
    - cudatoolkit=11.7
    - cudatoolkit-dev=11.7
    - cudnn=8.4
    - sentencepiece
    - pip:
        - flax==0.6.8
        - optax==0.1.4
        - distrax==0.1.3
        - transformers==4.27.2
        - huggingface_hub==0.13.3
        - datasets==2.9.0
        - einops
        - tensorflow==2.11.0
        - dill
        - seaborn
        - absl-py
        - gtimer
        - joblib
        - wandb==0.13.5
        - ml_collections
        - gcsfs==2022.11.0
        - requests
        - jupyter_http_over_ws
        - lm-eval==0.3.0
        - mlxu==0.1.9
        - pydantic
        - fastapi
        - uvicorn
        - gradio
